# CreditOne Preprocessing
Class 5 Task 3

#### Import modules

In [1]:
#imports
#numpy,pandas,scipy,math,matplotlib
import numpy as np
import pandas as pd
import scipy

#### import data

In [2]:
#data
rawData = pd.read_csv('default of credit card clients.csv', header=1)
rawData.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0   4810     500000    1          3         3   53      0      0      0   
1  15096     500000    1          1         3   38     -2     -2     -2   
2     81     470000    2          3         3   33      0      0      0   
3  14889     450000    2          1         3   37      1     -2     -2   
4  11072     450000    1          1         3   37     -2     -2     -2   

   PAY_4             ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  \
0      0             ...                 125218     126650     114473   
1     -2             ...                      0          0          0   
2      0             ...                  69923      29271      29889   
3     -2             ...                      0          0          0   
4     -2             ...                    317       1614        324   

   PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0     12602     11000      4711      6000     11000     10000   
1         0         0         0         0         0         0   
2      6400      7566      3000       960      1000      3000   
3         0         0         0         0         0         0   
4       303      5041         1      1622       325       316   

   default payment next month  
0                           0  
1                           1  
2                           0  
3                           0  
4                           0  

[5 rows x 25 columns]

In [4]:
df = rawData

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
ID                            30000 non-null int64
LIMIT_BAL                     30000 non-null int64
SEX                           30000 non-null category
EDUCATION                     30000 non-null category
MARRIAGE                      30000 non-null category
AGE                           30000 non-null category
PAY_0                         30000 non-null int64
PAY_2                         30000 non-null int64
PAY_3                         30000 non-null int64
PAY_4                         30000 non-null int64
PAY_5                         30000 non-null int64
PAY_6                         30000 non-null int64
BILL_AMT1                     30000 non-null int64
BILL_AMT2                     30000 non-null int64
BILL_AMT3                     30000 non-null int64
BILL_AMT4                     30000 non-null int64
BILL_AMT5                     30000 non-null int64
BILL_AMT6   

In [13]:
df['AGE'] = pd.cut(df['AGE'], [20,30,40,50,60,70,80],labels=['20-30','30-40','40-50', '50-60', '60-70','80-70'])

In [15]:
df.SEX = df.SEX.astype('category')
df.EDUCATION = df.EDUCATION.astype('category')
df.MARRIAGE = df.MARRIAGE.astype('category')
df.AGE_bin = df.AGE.astype('category')

In [36]:
df.AGE.value_counts()

20-30    11013
30-40    10713
40-50     6005
50-60     1997
60-70      257
80-70       15
Name: AGE, dtype: int64

In [37]:
df.SEX.value_counts()

2    18112
1    11888
Name: SEX, dtype: int64

In [38]:
df.EDUCATION.value_counts()

2    14030
1    10585
3     4917
4      468
Name: EDUCATION, dtype: int64

In [40]:
df.MARRIAGE.value_counts()

2    15964
1    13659
3      323
0       54
Name: MARRIAGE, dtype: int64

In [54]:
SEX_dummies = pd.get_dummies(df['SEX'],prefix = "SEX", columns=None, sparse=False, drop_first=False)
MARRIAGE_dummies = pd.get_dummies(df['MARRIAGE'],prefix = "MARRIAGE", columns=None, sparse=False, drop_first=False)
EDUCATION_dummies = pd.get_dummies(df['EDUCATION'],prefix = "EDUCATION", columns=None, sparse=False, drop_first=False)
AGE_dummies = pd.get_dummies(df['AGE'],prefix = "AGE", columns=None, sparse=False, drop_first=False)

In [58]:
MARRIAGE_dummies
#EDUCATION_dummies
#AGE_dummies
#SEX_dummies

MARRIAGE_0  MARRIAGE_1  MARRIAGE_2  MARRIAGE_3
0               0           0           0           1
1               0           0           0           1
2               0           0           0           1
3               0           0           0           1
4               0           0           0           1
5               0           0           0           1
6               0           0           0           1
7               0           0           0           1
8               0           0           0           1
9               0           0           0           1
10              0           0           0           1
11              0           0           0           1
12              0           0           0           1
13              0           0           0           1
14              0           0           0           1
15              0           0           0           1
16              0           0           0           1
17              0           0           0           1
18              0           0           0           1
19              0           0           0           1
20              0           0           0           1
21              0           0           0           1
22              0           0           0           1
23              0           0           0           1
24              0           0           0           1
25              0           0           0           1
26              0           0           0           1
27              0           0           0           1
28              0           0           0           1
29              0           0           0           1
...           ...         ...         ...         ...
29970           1           0           0           0
29971           1           0           0           0
29972           1           0           0           0
29973           1           0           0           0
29974           1           0           0           0
29975           1           0           0           0
29976           1           0           0           0
29977           1           0           0           0
29978           1           0           0           0
29979           1           0           0           0
29980           1           0           0           0
29981           1           0           0           0
29982           1           0           0           0
29983           1           0           0           0
29984           1           0           0           0
29985           1           0           0           0
29986           1           0           0           0
29987           1           0           0           0
29988           1           0           0           0
29989           1           0           0           0
29990           1           0           0           0
29991           1           0           0           0
29992           1           0           0           0
29993           1           0           0           0
29994           1           0           0           0
29995           1           0           0           0
29996           1           0           0           0
29997           1           0           0           0
29998           1           0           0           0
29999           1           0           0           0

[30000 rows x 4 columns]

In [71]:
#del df['MARRIAGE']
#del df['SEX']
#del df['EDUCATION']
del df['AGE']

In [93]:

#EDUCATION_dummies
#AGE_dummies
#SEX_dummies
df2=df2.join(SEX_dummies)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 37 columns):
ID                            30000 non-null int64
LIMIT_BAL                     30000 non-null int64
PAY_0                         30000 non-null int64
PAY_2                         30000 non-null int64
PAY_3                         30000 non-null int64
PAY_4                         30000 non-null int64
PAY_5                         30000 non-null int64
PAY_6                         30000 non-null int64
BILL_AMT1                     30000 non-null int64
BILL_AMT2                     30000 non-null int64
BILL_AMT3                     30000 non-null int64
BILL_AMT4                     30000 non-null int64
BILL_AMT5                     30000 non-null int64
BILL_AMT6                     30000 non-null int64
PAY_AMT1                      30000 non-null int64
PAY_AMT2                      30000 non-null int64
PAY_AMT3                      30000 non-null int64
PAY_AMT4                

In [99]:
df=df2

In [103]:
df.to_csv('out.csv')

## Select Features


### Remove low variance features

In [46]:
from sklearn.feature_selection import VarianceThreshold

In [47]:
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
sel.fit_transform(df)

array([[  4810, 500000,      1, ...,  11000,  10000,      0],
       [ 15096, 500000,      1, ...,      0,      0,      1],
       [    81, 470000,      2, ...,   1000,   3000,      0],
       ..., 
       [ 16582,  20000,      1, ...,      0,      0,      0],
       [ 21560,  20000,      2, ...,    531,    400,      0],
       [  6390,  10000,      1, ...,      0,      0,      0]])

In [48]:
df.shape

(30000, 25)

In [17]:
#features
features = rawData.iloc[:,1:24]
print('Summary of feature sample')
features.head()

Summary of feature sample


LIMIT_BAL SEX EDUCATION MARRIAGE    AGE  PAY_0  PAY_2  PAY_3  PAY_4  PAY_5  \
0     500000   1         3        3  50-60      0      0      0      0      0   
1     500000   1         1        3  30-40     -2     -2     -2     -2     -2   
2     470000   2         3        3  30-40      0      0      0      0      0   
3     450000   2         1        3  30-40      1     -2     -2     -2     -2   
4     450000   1         1        3  30-40     -2     -2     -2     -2     -2   

     ...     BILL_AMT3  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0    ...        426103     125218     126650     114473     12602     11000   
1    ...             0          0          0          0         0         0   
2    ...        162702      69923      29271      29889      6400      7566   
3    ...             0          0          0          0         0         0   
4    ...          5018        317       1614        324       303      5041   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  
0      4711      6000     11000     10000  
1         0         0         0         0  
2      3000       960      1000      3000  
3         0         0         0         0  
4         1      1622       325       316  

[5 rows x 23 columns]

# **************stop**************

#### Select Dependent Variable

In [18]:
#dependent variable
depVar = df['default payment next month']

In [19]:
depVar.describe()

count    30000.000000
mean         0.221200
std          0.415062
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: default payment next month, dtype: float64

### Establish Training Data


In [28]:
#run split
X_train, X_test, y_train, y_test = train_test_split(features, depVar, test_size = 0.30, random_state =123)
print("X_train",X_train.shape,'\n',"X_test", X_test.shape,'\n',"y_train", y_train.shape,'\n',"y_test", y_test.shape)

X_train (21000, 23) 
 X_test (9000, 23) 
 y_train (21000,) 
 y_test (9000,)


In [29]:
X_test.describe()

LIMIT_BAL        PAY_0        PAY_2        PAY_3        PAY_4  \
count    9000.000000  9000.000000  9000.000000  9000.000000  9000.000000   
mean   166248.186667    -0.014222    -0.112889    -0.151333    -0.206778   
std    129030.764200     1.128492     1.209167     1.205051     1.182539   
min     10000.000000    -2.000000    -2.000000    -2.000000    -2.000000   
25%     50000.000000    -1.000000    -1.000000    -1.000000    -1.000000   
50%    140000.000000     0.000000     0.000000     0.000000     0.000000   
75%    232500.000000     0.000000     0.000000     0.000000     0.000000   
max    780000.000000     8.000000     7.000000     8.000000     8.000000   

             PAY_5        PAY_6      BILL_AMT1      BILL_AMT2      BILL_AMT3  \
count  9000.000000  9000.000000    9000.000000    9000.000000    9000.000000   
mean     -0.252000    -0.280111   50839.135444   48589.317000   46512.621111   
std       1.143084     1.165056   73012.738740   69928.882208   67853.283672   
min      -2.000000    -2.000000  -11545.000000  -69777.000000 -157264.000000   
25%      -1.000000    -1.000000    3601.750000    3126.500000    2919.750000   
50%       0.000000     0.000000   21941.000000   20921.000000   19996.500000   
75%       0.000000     0.000000   67273.750000   63824.750000   59628.250000   
max       8.000000     8.000000  653062.000000  671563.000000  693131.000000   

           BILL_AMT4      BILL_AMT5      BILL_AMT6       PAY_AMT1  \
count    9000.000000    9000.000000    9000.000000    9000.000000   
mean    42980.065889   39932.711889   38437.033111    5903.349111   
std     63596.219699   59788.155564   58441.461871   16944.383109   
min   -170000.000000  -19205.000000 -150953.000000       0.000000   
25%      2400.000000    1803.750000    1229.000000    1000.000000   
50%     19185.500000   18056.500000   16754.500000    2130.000000   
75%     54850.500000   50377.750000   49048.500000    5019.000000   
max    706864.000000  547880.000000  514975.000000  368199.000000   

            PAY_AMT2       PAY_AMT3       PAY_AMT4       PAY_AMT5  \
count    9000.000000    9000.000000    9000.000000    9000.000000   
mean     6045.809000    5510.244889    4851.749778    4749.373667   
std     18575.093746   18320.253133   16358.917726   14951.192543   
min         0.000000       0.000000       0.000000       0.000000   
25%       870.250000     390.000000     310.750000     249.250000   
50%      2003.500000    1800.000000    1500.000000    1500.000000   
75%      5000.000000    4529.500000    4106.000000    4069.000000   
max    401003.000000  417588.000000  528897.000000  417990.000000   

            PAY_AMT6  
count    9000.000000  
mean     5543.712556  
std     19951.672468  
min         0.000000  
25%       100.000000  
50%      1500.000000  
75%      4003.000000  
max    528666.000000

In [30]:
X_train.describe()

LIMIT_BAL         PAY_0         PAY_2         PAY_3         PAY_4  \
count    21000.000000  21000.000000  21000.000000  21000.000000  21000.000000   
mean    168014.095238     -0.017762     -0.142714     -0.172571     -0.226619   
std     130053.159397      1.121810      1.191931      1.193315      1.163326   
min      10000.000000     -2.000000     -2.000000     -2.000000     -2.000000   
25%      50000.000000     -1.000000     -1.000000     -1.000000     -1.000000   
50%     140000.000000      0.000000      0.000000      0.000000      0.000000   
75%     240000.000000      0.000000      0.000000      0.000000      0.000000   
max    1000000.000000      8.000000      8.000000      8.000000      7.000000   

              PAY_5         PAY_6      BILL_AMT1      BILL_AMT2     BILL_AMT3  \
count  21000.000000  21000.000000   21000.000000   21000.000000  2.100000e+04   
mean      -0.272286     -0.295810   51387.986095   49431.828667  4.722767e+04   
std        1.128892      1.143465   73902.423155   71700.839216  6.998128e+04   
min       -2.000000     -2.000000 -165580.000000  -33350.000000 -6.150600e+04   
25%       -1.000000     -1.000000    3527.750000    2913.750000  2.585250e+03   
50%        0.000000      0.000000   22476.000000   21335.500000  2.014450e+04   
75%        0.000000      0.000000   67070.500000   64122.750000  6.037675e+04   
max        7.000000      8.000000  964511.000000  983931.000000  1.664089e+06   

           BILL_AMT4      BILL_AMT5      BILL_AMT6       PAY_AMT1  \
count   21000.000000   21000.000000   21000.000000   21000.000000   
mean    43384.184571   40473.696286   39058.072095    5560.822524   
std     64647.113535   61225.187647   60025.055650   16396.574970   
min    -81334.000000  -81334.000000 -339603.000000       0.000000   
25%      2301.000000    1748.500000    1261.000000    1000.000000   
50%     19001.000000   18127.500000   17181.000000    2100.000000   
75%     54276.250000   50054.250000   49267.750000    5005.000000   
max    891586.000000  927171.000000  961664.000000  873552.000000   

           PAY_AMT2       PAY_AMT3       PAY_AMT4      PAY_AMT5       PAY_AMT6  
count  2.100000e+04   21000.000000   21000.000000   21000.00000   21000.000000  
mean   5.867744e+03    5103.725762    4815.074190    4820.82219    5074.841143  
std    2.470914e+04   17291.273856   15360.088627   15416.67454   16758.087519  
min    0.000000e+00       0.000000       0.000000       0.00000       0.000000  
25%    8.240000e+02     390.000000     284.000000     253.75000     122.750000  
50%    2.012000e+03    1804.000000    1500.000000    1508.50000    1500.000000  
75%    5.000000e+03    4500.000000    4000.000000    4017.50000    4000.000000  
max    1.684259e+06  896040.000000  621000.000000  426529.00000  527143.000000

In [31]:
y_test.describe()

count    9000.000000
mean        0.222778
std         0.416133
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: default payment next month, dtype: float64

In [32]:
y_train.describe()

count    21000.000000
mean         0.220524
std          0.414610
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: default payment next month, dtype: float64

# SVM
http://scikit-learn.org/stable/modules/svm.html#classification

In [33]:
SVMclf = svm.SVC()

In [34]:
SVMclf.fit(X_train, y_train)

ValueError: could not convert string to float: '30-40'

In [27]:
SVMclf_pred = SVMclf.predict(X_test)

NotFittedError: This SVC instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [60]:
print(" ***Support Vector Machine***","\n","accuracy",skm.accuracy_score(y_test, SVMclf_pred),'\n',"average_precision_score",skm.average_precision_score(y_test, SVMclf_pred),'\n',"Kappa",skm.cohen_kappa_score(y_test, SVMclf_pred),'\n','Precission Score',skm.precision_score(y_test,SVMclf_pred))

 ***Support Vector Machine*** 
 accuracy 0.778222222222 
 average_precision_score 0.228639920666 
 Kappa 0.0199367901784 
 Precission Score 0.578947368421


In [88]:
SVMclf.score(X_test, y_test) 

0.77822222222222226

# Stochastic Gradient Descent

http://scikit-learn.org/stable/modules/sgd.html#classification

In [61]:
SDGclf = SGDClassifier(loss="hinge", penalty="l2")

In [62]:
SDGclf.fit(X_train, y_train)

/Users/degraff/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [63]:
SDGclf_pred = SDGclf.predict(X_test)

In [64]:
print(" ***Stochastic Gradient Descent***","\n","accuracy",skm.accuracy_score(y_test, SDGclf_pred),'\n',"average_precision_score",skm.average_precision_score(y_test, SDGclf_pred),'\n',"Kappa",skm.cohen_kappa_score(y_test, SDGclf_pred),'\n','Precission Score',skm.precision_score(y_test,SDGclf_pred))

 ***Stochastic Gradient Descent*** 
 accuracy 0.689444444444 
 average_precision_score 0.230326308651 
 Kappa 0.0402020097189 
 Precission Score 0.258557457213


In [89]:
SDGclf.score(X_test, y_test) 

0.68944444444444442

In [90]:
#same as accuracy_score(y_test,clf_pred)
NCCclf.score(X_test, y_test) 

0.53133333333333332

# Nearest Centroid Classifier

http://scikit-learn.org/stable/modules/neighbors.html#nearest-neighbors-classification

In [65]:
NCCclf = NearestCentroid()

In [66]:
NCCclf.fit(X_train, y_train)

NearestCentroid(metric='euclidean', shrink_threshold=None)

In [67]:
NCCclf_pred = NCCclf.predict(X_test)

In [68]:
print(" ***Nearest Centroid Classifier***","\n","accuracy",skm.accuracy_score(y_test, NCCclf_pred),'\n',"average_precision_score",skm.average_precision_score(y_test, NCCclf_pred),'\n',"Kappa",skm.cohen_kappa_score(y_test, NCCclf_pred),'\n','Precision Score',skm.precision_score(y_test,NCCclf_pred))

 ***Nearest Centroid Classifier*** 
 accuracy 0.531333333333 
 average_precision_score 0.257792545966 
 Kappa 0.108053947205 
 Precision Score 0.274781192754


In [90]:
#same as accuracy_score(y_test,clf_pred)
NCCclf.score(X_test, y_test) 

0.53133333333333332

# Nearest Centroid Classifier

http://scikit-learn.org/stable/modules/neighbors.html#nearest-neighbors-classification

In [82]:
KNNclf = KNeighborsClassifier(n_neighbors=30)

In [83]:
KNNclf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=30, p=2,
           weights='uniform')

In [87]:
KNNclf.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': 1,
 'n_neighbors': 30,
 'p': 2,
 'weights': 'uniform'}

In [84]:
KNNclf_pred = KNNclf.predict(X_test)

In [86]:
print(" ***K-Nearest Neighbor Classifier***","\n","accuracy",skm.accuracy_score(y_test, KNNclf_pred),'\n',"average_precision_score",skm.average_precision_score(y_test, KNNclf_pred),'\n',"Kappa",skm.cohen_kappa_score(y_test, KNNclf_pred),'\n','Precision Score',skm.precision_score(y_test,KNNclf_pred))

 ***K-Nearest Neighbor Classifier*** 
 accuracy 0.776666666667 
 average_precision_score 0.243180772449 
 Kappa 0.0764239994976 
 Precision Score 0.491909385113


In [87]:
KNNclf.get_params()

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': 1,
 'n_neighbors': 30,
 'p': 2,
 'weights': 'uniform'}

In [91]:
KNNclf.score(X_test, y_test) 

0.77666666666666662

# Decision Tree Classifer

http://scikit-learn.org/stable/modules/tree.html#classification

In [ ]:
DTclf = tree.DecisionTreeClassifier()

In [ ]:
DTclf.fit(X_train, y_train)

In [ ]:
DTclf_pred = DTclf.predict(X_test)

In [ ]:
print(" ***Decision Tree Classifier***" ,'\n',"accuracy",skm.accuracy_score(y_test, DTclf_pred),'\n',"average_precision_score",skm.average_precision_score(y_test, DTclf_pred),'\n',"Kappa",skm.cohen_kappa_score(y_test, DTclf_pred),'\n','Precision Score',skm.precision_score(y_test,DTclf_pred))

# Multi-layer Perceptron

http://scikit-learn.org/stable/modules/neural_networks_supervised.html#classification

In [ ]:
MLPclf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(100,), random_state=1)

In [ ]:
MLPclf.fit(X_train, y_train)

In [ ]:
MLPclf_pred = MLPclf.predict(X_test)

In [ ]:
print(" ***Multi-layer Perceptron***" ,'\n',"accuracy",skm.accuracy_score(y_test, MLPclf_pred),'\n',"average_precision_score",skm.average_precision_score(y_test, MLPclf_pred),'\n',"Kappa",skm.cohen_kappa_score(y_test, MLPclf_pred),'\n','Precision Score',skm.precision_score(y_test,MLPclf_pred))

## Making Predictions

# Tuning

In [95]:
scores = cross_val_score(SVMclf, X_train, y_train, cv=15)
scores

array([ 0.78087081,  0.77872948,  0.78301213,  0.77944325,  0.77785714,
        0.77714286,  0.78      ,  0.78      ,  0.77857143,  0.78428571,
        0.78142857,  0.78270193,  0.77698356,  0.78055754,  0.78198713])

In [96]:
scores = cross_val_score(SDGclf, X_train, y_train, cv=15)
scores

/Users/degraff/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/Users/degraff/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
/Users/degra

array([ 0.77872948,  0.76802284,  0.64882227,  0.77944325,  0.49071429,
        0.77928571,  0.77142857,  0.77928571,  0.77571429,  0.75      ,
        0.77928571,  0.71265189,  0.77984274,  0.64903503,  0.77841315])

In [94]:
scores = cross_val_score(NCCclf, X_train, y_train, cv=15)
scores

array([ 0.5267666 ,  0.52462527,  0.53961456,  0.54246966,  0.54714286,
        0.56357143,  0.50857143,  0.52642857,  0.53071429,  0.53571429,
        0.54357143,  0.5196569 ,  0.5382416 ,  0.5375268 ,  0.53323803])

In [94]:
scores = cross_val_score(DTclf, X_train, y_train, cv=15)
scores

array([ 0.5267666 ,  0.52462527,  0.53961456,  0.54246966,  0.54714286,
        0.56357143,  0.50857143,  0.52642857,  0.53071429,  0.53571429,
        0.54357143,  0.5196569 ,  0.5382416 ,  0.5375268 ,  0.53323803])

In [94]:
scores = cross_val_score(NCCclf, X_train, y_train, cv=15)
scores

array([ 0.5267666 ,  0.52462527,  0.53961456,  0.54246966,  0.54714286,
        0.56357143,  0.50857143,  0.52642857,  0.53071429,  0.53571429,
        0.54357143,  0.5196569 ,  0.5382416 ,  0.5375268 ,  0.53323803])